t3: 1.0
#####################################
# 対象言語
#####################################
languages:
  - ja_JP
#####################################
# カスタム機能定義
#####################################
info:
  name: csv
  customPackage: com.epion_t3.csv
  summary:
    - lang: ja_JP
      contents: "CSVを扱う機能を提供します。"
  description:
    - lang: ja_JP
      contents: "CSVを扱う機能を提供します。"
#####################################
# 設定定義
#####################################
configurations:
  ####################################
  # FileFormatConfiguration
  ####################################
  - id: FileFormatConfiguration
    summary:
      - lang: ja_JP
        contents: "CSV/TSVファイルのフォーマットを定義するための設定定義です。"
    description:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "CSV/TSVファイルのフォーマットを定義するための設定定義です。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "本設定定義は、「Commons CSV」の「CSVFormat」をベースとしています。"
    structure:
      - order: 1
        name: configuration
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "「FileFormatConfiguration」固定"
      - order: 2
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "設定のID"
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "設定の概要（任意）"
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "設定の詳細（任意）"
      - order: 5
        name: "delimiter"
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "要素のデリミタ文字を指定します。省略した場合、カンマ（,）が選択されます。"
      - order: 6
        name: "escape"
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "エスケープに使用する文字を指定します。"
      - order: 7
        name: "ignoreEmptyLines"
        required: false
        type: boolean
        summary:
          - lang: ja_JP
            contents: "空行をSKIPするかを真偽値で指定します。true の場合SKIPします。"
      - order: 8
        name: "quote"
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "要素の囲い文字を指定します。"
      - order: 9
        name: "recordSeparator"
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "レコード区切り文字を指定します。改行コードの指定となりますが、「CRLF」もしくは「LF」のいずれかを指定して下さい。"
      - order: 10
        name: "trim"
        required: false
        type: boolean
        summary:
          - lang: ja_JP
            contents: "要素の前後の空白を除去するかを真偽値で指定します。true の場合Trim処理を行います。デフォルトでは falseと扱います。"
      - order: 11
        name: "firstRecordIsHeader"
        required: false
        type: boolean
        summary:
          - lang: ja_JP
            contents: "1レコード目がヘッダを表すかどうかを真偽値で指定します。 trueの場合、ヘッダ行を比較SKIPします。デフォルトでは falseと扱います。"
#####################################
# コマンド定義
#####################################
commands:
  ##########################
  # AssertCsvData
  ##########################
  - id: AssertCsvData
    evidenceCommand: false
    assertCommand: true
    summary:
      - lang: ja_JP
        contents: "CSVの値を確認します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents:
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "CSVファイル同士を比較し、値の確認を行います。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "結果値のCSVファイルは、エビデンスとして取得済である必要があります。"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "ファイルフォーマットの指定及び無視カラムインデックスの指定である程度柔軟なアサーションが行えます。"
      - order: 4
        summary:
          - lang: ja_JP
            contents: "ファイルフォーマットの指定次第でTSVにも対応が可能となっています。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AssertCSVData」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: fileFormatConfigRef
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "ファイルフォーマット定義の参照ID # (1)"
        description:
          - lang: ja_JP
            contents: "ファイルフォーマットの設定を行っている `Configuration` の参照IDを指定します。"
      - order: 6
        name: expectedDataSetPath
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "期待値CSV/TSVの相対パス # (2)"
        description:
          - lang: ja_JP
            contents: "期待値を定義したCSV/TSVファイルへの相対パス。基底ディレクトリはパス解決モードで指定された方式に従います。"
      - order: 7
        name: actualFlowId
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "結果値を取得したFlowのFlowIDを指定 # (3)"
        description:
          - lang: ja_JP
            contents: "結果値を取得したFlowIDを指定。"
      - order: 8
        name: ignores
        required: false
        type: array
        summary:
          - lang: ja_JP
            contents: |
              対象のCSV/TSV内でアサートの対象外としたいカラムのIndex指定を行います。
              例：
                ignores:
                  - index: 1（headerNameかindexのいずれかが必須）
                    headerName: ヘッダ名（現状は、「FileFormatConfiguration」の「firstRecordIsHeader」がTrueの場合のみ利用可能。）
      - order: 9
        name: ignoresConfigPath
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents:  |
              対象のCSV/TSV内でアサートの対象外としたいカラムの設定を記載した設定ファイルのパスを指定します。
              設定ファイルは、YAML or JSON で指定します。
              例：{ "ignores" : [
                {
                  "index" : "インデックスの数値を指定。headerNameかindexのいずれかが必須",
                  "headerName" : "ヘッダ名を指定。現状は、「FileFormatConfiguration」の「firstRecordIsHeader」がTrueの場合のみ利用可能。"
                }
              ]}
#####################################
# メッセージ定義
#####################################
messages:
  - id: "com.epion_t3.csv.err.0001"
    message:
      - lang: ja_JP
        contents: "期待値ファイルが見つかりません. Path: {0}"
  - id: "com.epion_t3.csv.err.0002"
    message:
      - lang: ja_JP
        contents: "期待値ファイルのCSV/TSV読み込みに失敗しました. Path: {0}"
  - id: "com.epion_t3.csv.err.0003"
    message:
      - lang: ja_JP
        contents: "期待値ファイルのパスは必須です."
  - id: "com.epion_t3.csv.err.0004"
    message:
      - lang: ja_JP
        contents: "結果値を取得したFlowIDは必須です."
  - id: "com.epion_t3.csv.err.0005"
    message:
      - lang: ja_JP
        contents: "指定されたエンコーディングは不正です. エンコーディング : {0}"
  - id: "com.epion_t3.csv.err.0006"
    message:
      - lang: ja_JP
        contents: "無視カラムの指定には、ヘッダ名称かインデックスの指定のいずれかが必須です."
  - id: "com.epion_t3.csv.err.0007"
    message:
      - lang: ja_JP
        contents: "比較無視カラムの設定ファイルは「yaml」「yml」「json」のいずれかで指定して下さい. 比較無視カラム設定ファイル : {0}"
  - id: "com.epion_t3.csv.err.0008"
    message:
      - lang: ja_JP
        contents: "比較無視カラムの設定ファイルが見つかりません. 比較無視カラム設定ファイル : {0}"
  - id: "com.epion_t3.csv.err.0009"
    message:
      - lang: ja_JP
        contents: "比較無視カラムの設定ファイルを正しく読み込めませんでした. 比較無視カラム設定ファイル : {0}"